# Exploratory Data Analysis

In [3]:
# Imports 
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

# Display all columns 
pd.set_option('display.max_columns', None)

In [2]:
# Accessing local database 
database_path = "/Users/jpuray/databases/medicalCases.db"
conn = sqlite3.connect(database_path)

## 1) Cleaning the data

In [5]:
pd.read_sql(
    """
    SELECT DISTINCT [Opioid Related]
    FROM cases 
    """, conn)

    Opioid Related
0       Non-Opioid
1           Opioid
2  Opioid-Fentanyl
3   Non-Disclosure
4

In [6]:
cases = pd.read_sql(
    """
    SELECT *
    FROM cases
    WHERE [Opioid Related] = 'Opioid-Fentanyl'
    """, conn
)
cases

,Row Number,Year,Quarter,Age in Years,Death Date,Security Status,Gender,Race,Ethnic Group (Standardized),Manner of Death,Manner Type,Manner Type (Standardized),Manner Sub Type,Manner Sub Type (Standardized),Opioid Related,Coronado Bridge Related (Suicide Cases),Cause of Death,Contributing Conditions,How Injury Occurred,Event Date,Event Time,Event Place,Event Place Type,Event City,Event Zip,Death Place,Death Place Type,Death City,Death Zip,Res City,Res Zip,Age Group Option 1,Age Group Option 2,Age Group Option 3
0,286,1997,Q4,59,12/15/1997,Access Free,Female,White,White,Accident,Medication,Drug - Medication - Alcohol,,Medication,Opioid-Fentanyl,FALSE,Pending laboratory studies,None,Self-administered overdose of amitriptyline & ...,12/15/1997,10:30:00 PM,Undetermined,Other,,,FOUND: Home (rental),Other,Lemon Grove,91945,Lemon Grove,91945,50 to 59,55 to 59,55 to 64
1,331,1997,Q1,39,01/23/1997,Access Free,Male,White,White,Accident,Alcohol-Medication,Drug - Medication - Alcohol,,Medication,Opioid-Fentanyl,FALSE,"Acute fentanyl, morphine, oxycodone & diazepam...",None,"Self-administered overdose of fentanyl, morphi...",1/23/1997,6:05:00 PM,Home,Other,,,Paradise Valley Hospital,Other,National City,91950,San Diego,92114,30 to 39,35 to 39,35 to 44
2,2557,1998,Q1,41,02/09/1998,Access Free,Male,White,White,Accident,Medication,Drug - Medication - Alcohol,,Medication,Opioid-Fentanyl,FALSE,Acute fentanyl intoxication,None,Self-administered overdose of fentanyl.,2/9/1998,7:15:00 AM,Apartment,Other,,,Apartment,Other,Lakeside,92040,Lakeside,92040,40 to 49,40 to 44,35 to 44
3,2762,1998,Q2,36,04/10/1998,Access Free,Male,White,White,Accident,,Drug - Medication - Alcohol,,Medication,Opioid-Fentanyl,FALSE,Acute fentanyl intoxication,None,Self-administered overdose of fentanyl.,4/10/1998,4:30:00 PM,Home,Other,,,Home,Other,Oceanside,92056,Oceanside,92056,30 to 39,35 to 39,35 to 44
4,4857,1999,Q3,36,07/07/1999,Access Free,Male,White,White,Accident,Medication,Drug - Medication - Alcohol,,Medication,Opioid-Fentanyl,FALSE,Anoxic encephalopathy due to: Therapeutic fent...,None,Adverse reaction to medication while in hospital.,11/6/1998,,Hospital,Other,,,Palomar Continuing Care,Other,Escondido,92025,Oceanside,92054,30 to 39,35 to 39,35 to 44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3450,80391,2024,Q1,38,01/16/2024,Access Free,Female,White,White,Accident,Drug - Medication,Drug - Medication - Alcohol,Drugs of abuse,Drugs of Abuse,Opioid-Fentanyl,,Anoxic-ischemic encephalopathy due to: resusci...,none,Self-administered fentanyl and methamphetamine,1/10/2024,Unknown,Home,Decedent's Home,San Diego,92114,,Hospital,La Mesa,91942,Boulevard,91905,30 to 39,35 to 39,35 to 44
3451,80392,2024,Q1,40,01/22/2024,Access Free,Male,White,White,Accident,Drug - Medication,Drug - Medication - Alcohol,Drugs of abuse,Drugs of Abuse,Opioid-Fentanyl,,Complications of anoxic-ischemic encephalopath...,None,self-administered fentanyl and methamphetamine,1/10/2024,Unknown,Home,Decedent's Home,El Cajon,92019,,Hospital,La Mesa,91942,El Cajon,92019,40 to 49,40 to 44,35 to 44
3452,80393,2024,Q1,26,01/08/2024,Access Free,Male,White,White,Accident,Drug - Medication,Drug - Medication - Alcohol,Drugs of abuse,Drugs of Abuse,Opioid-Fentanyl,,Complications of anoxic-ischemic encephalopath...,None,Self-administered fentanyl,6/15/2023,1600,Home,General Location (Manual Entry),Oceanside,92054,Carmel Mountain Rehabilitation Healthcare Center,General Location (Manual Entry),San Diego,92128,Sparks,74869,20 to 29,25 to 29,25 to 34
3453,80397,2024,Q1,52,02/15/2024,Access Free,Female,White,White,Accident,Drug - Medication,Drug - Medication - Alcohol,Drugs of abuse,Drugs of Abuse,Opioid-Fentanyl,,Anoxic encephalopathy due to: Resuscitated car...,None,Self-administered fentanyl and amphetamine,02/10/2024,Unknown,,,,,,Hospital,La Mesa,91942,Lakeside,92040,50 to 59,50 to 54,45 to 54
3454,80399,2024,Q1,48,02/17/2024,Access Free,Male,White,White,Accident,Drug - Medication,Drug - Medication - Alcohol,Drugs of abuse,Drugs of Abuse,Opioid-Fentanyl,,Anoxic encephalopathy due to: Resuscitated car...,None,Self-administered fentanyl and methamphetamine,02/06/2024,Unknown,Hotel,General Location (Manual Entry),San Diego,92109,,Hospital,La Jolla,92037,,,40 to 49,45 to 49,45 to 54

In [23]:
# Filtering data for only Fentanyl deaths 
df = df[df['Opioid Related'] == 'Opioid-Fentanyl'] 

# Converting the Event Date and Event Time to datetime
#df['Event Date'] = df['Event Date'].apply(lambda x:  np.nan if x == 'Unk' else pd.to_datetime(x))
df['Event Time'] = df['Event Time'].apply(lambda x:  np.nan if x == 'Unk' else pd.to_datetime(x))

OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1127, at position 0

In [17]:
#

Row Number                                   int64
Year                                         int64
Quarter                                     object
Age in Years                               float64
Death Date                                  object
Security Status                             object
Gender                                      object
Race                                        object
Ethnic Group (Standardized)                 object
Manner of Death                             object
Manner Type                                 object
Manner Type (Standardized)                  object
Manner Sub Type                             object
Manner Sub Type (Standardized)              object
Opioid Related                              object
Coronado Bridge Related (Suicide Cases)     object
Cause of Death                              object
Contributing Conditions                     object
How Injury Occurred                         object
Event Date                                  object
Event Time                                  object
Event Place                                 object
Event Place Type                            object
Event City                                  object
Event Zip                                   object
Death Place                                 object
Death Place Type                            object
Death City                                  object
Death Zip                                   object
Res City                                    object
Res Zip                                     object
Age Group Option 1                          object
Age Group Option 2                          object
Age Group Option 3                          object
dtype: object

In [18]:
df.describe()

         Row Number         Year  Age in Years
count   3322.000000  3322.000000   3321.000000
mean   66350.892535  2020.221252     41.227341
std    12425.172069     3.883906     13.500975
min      286.000000  1997.000000      0.000000
25%    64132.250000  2020.000000     31.000000
50%    68537.500000  2021.000000     39.000000
75%    72982.750000  2022.000000     52.000000
max    80353.000000  2023.000000     98.000000